site_name: Test docs
site_description: 'A docs test'
site_author: 'Kasper Skytte Andersen'
docs_dir: docs/
repo_name: 'cmc-aau/hpc-docs'
repo_url: 'https://github.com/cmc-aau/hpc-docs'
nav:
    - Home: index.md
theme:
  name: 'material'
